In [2]:
%run 006data-edits.ipynb

006data-edits.ipynb:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  {
006data-edits.ipynb:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  "cell_type": "code",
006data-edits.ipynb:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  "import pandas as pd\n",


In [3]:
test

ID  shop_id  item_id
0            0        5     5037
1            1        5     5320
2            2        5     5233
3            3        5     5232
4            4        5     5268
...        ...      ...      ...
214195  214195       45    18454
214196  214196       45    16188
214197  214197       45    15757
214198  214198       45    19648
214199  214199       45      969

[214200 rows x 3 columns]

In [4]:
sub

ID  item_cnt_month
0            0             0.5
1            1             0.5
2            2             0.5
3            3             0.5
4            4             0.5
...        ...             ...
214195  214195             0.5
214196  214196             0.5
214197  214197             0.5
214198  214198             0.5
214199  214199             0.5

[214200 rows x 2 columns]

In [5]:
print(len(shops))
print(len(items))

60
22170


In [6]:
len(items) * len(shops)

1330200

In [7]:
test.shop_id.unique()

array([ 5,  4,  6,  3,  2,  7, 10, 12, 28, 31, 26, 25, 22, 24, 21, 15, 16,
       18, 14, 19, 42, 50, 49, 53, 52, 47, 48, 57, 58, 59, 55, 56, 36, 37,
       35, 38, 34, 46, 41, 44, 39, 45], dtype=int64)

In [8]:
len(train.shop_id.unique()) - len(test.shop_id.unique())

18

In [9]:
len(train.item_id.unique()) - len(test.item_id.unique())

16707

In [10]:
len(test.shop_id.unique()) * len(test.item_id.unique()) == len(test) #なるほどねw

True

In [16]:
not_in_test_shop = np.setdiff1d(train.shop_id.unique(), test.shop_id.unique())
not_in_test_shop

array([ 0,  1,  8,  9, 11, 13, 17, 20, 23, 27, 29, 30, 32, 33, 40, 43, 51,
       54], dtype=int64)

In [17]:
shops

shop_name  shop_id  \
0                     !Якутск Орджоникидзе, 56 фран        0   
1                     !Якутск ТЦ "Центральный" фран        1   
2                                  Адыгея ТЦ "Мега"        2   
3                    Балашиха ТРК "Октябрь-Киномир"        3   
4                          Волжский ТЦ "Волга Молл"        4   
5                            Вологда ТРЦ "Мармелад"        5   
6                        Воронеж (Плехановская, 13)        6   
7                            Воронеж ТРЦ "Максимир"        7   
8                      Воронеж ТРЦ Сити-Парк "Град"        8   
9                                 Выездная Торговля        9   
10                       Жуковский ул. Чкалова 39м?       10   
11                       Жуковский ул. Чкалова 39м²       11   
12                              Интернет-магазин ЧС       12   
13                              Казань ТЦ "Бехетле"       13   
14                          Казань ТЦ "ПаркХаус" II       14   
15                             Калуга ТРЦ "XXI век"       15   
16                                 Коломна ТЦ "Рио"       16   
17                    Красноярск ТЦ "Взлетка Плаза"       17   
18                             Красноярск ТЦ "Июнь"       18   
19                            Курск ТЦ "Пушкинский"       19   
20                              Москва "Распродажа"       20   
21                           Москва МТРЦ "Афи Молл"       21   
22                               Москва Магазин С21       22   
23                 Москва ТК "Буденовский" (пав.А2)       23   
24                 Москва ТК "Буденовский" (пав.К7)       24   
25                              Москва ТРК "Атриум"       25   
26                      Москва ТЦ "Ареал" (Беляево)       26   
27                   Москва ТЦ "МЕГА Белая Дача II"       27   
28                  Москва ТЦ "МЕГА Теплый Стан" II       28   
29               Москва ТЦ "Новый век" (Новокосино)       29   
30                           Москва ТЦ "Перловский"       30   
31                          Москва ТЦ "Семеновский"       31   
32                       Москва ТЦ "Серебряный Дом"       32   
33                                Мытищи ТРК "XL-3"       33   
34                             Н.Новгород ТРЦ "РИО"       34   
35                      Н.Новгород ТРЦ "Фантастика"       35   
36            Новосибирск ТРЦ "Галерея Новосибирск"       36   
37                            Новосибирск ТЦ "Мега"       37   
38                                   Омск ТЦ "Мега"       38   
39            РостовНаДону ТРК "Мегацентр Горизонт"       39   
40  РостовНаДону ТРК "Мегацентр Горизонт" Островной       40   
41                           РостовНаДону ТЦ "Мега"       41   
42                           СПб ТК "Невский Центр"       42   
43                                  СПб ТК "Сенная"       43   
44                              Самара ТЦ "Мелодия"       44   
45                             Самара ТЦ "ПаркХаус"       45   
46                            Сергиев Посад ТЦ "7Я"       46   
47                           Сургут ТРЦ "Сити Молл"       47   
48                     Томск ТРЦ "Изумрудный Город"       48   
49                            Тюмень ТРЦ "Кристалл"       49   
50                               Тюмень ТЦ "Гудвин"       50   
51                        Тюмень ТЦ "Зеленый Берег"       51   
52                             Уфа ТК "Центральный"       52   
53                                 Уфа ТЦ "Семья" 2       53   
54                                  Химки ТЦ "Мега"       54   
55                         Цифровой склад 1С-Онлайн       55   
56                             Чехов ТРЦ "Карнавал"       56   
57                          Якутск Орджоникидзе, 56       57   
58                          Якутск ТЦ "Центральный"       58   
59                           Ярославль ТЦ "Альтаир"       59   

                                         shop_name_en         city  
0                     Yakutsk Ordzhonikidze, 56 franc      Yakutsk  

In [21]:
not_in_test_items = np.setdiff1d(train.item_id.unique(), test.item_id.unique())
not_in_test_items

array([    0,     1,     2, ..., 22165, 22168, 22169], dtype=int64)

In [22]:
len(not_in_test_items)

17070

In [31]:
len(items.unique())

AttributeError: 'DataFrame' object has no attribute 'unique'

In [26]:
len(train.item_id.unique())

21807

In [33]:
train.shape

(2935849, 11)

In [35]:
train.item_id

0          22154
1          22151
2           5603
3           5587
4           5613
           ...  
2935844    20231
2935845    20334
2935846    20339
2935847    20352
2935848    20602
Name: item_id, Length: 2935849, dtype: int64

In [37]:
set(train.item_id) - set(test.item_id) #行けそう

17070

In [27]:
len(test.item_id.unique())

5100

In [28]:
def get_in_test(x):
    if x.isin()

2047     42
19744    42
15406    42
13359    42
3240     42
         ..
21086    42
21214    42
17244    42
21342    42
2049     42
Name: item_id, Length: 5100, dtype: int64

In [29]:
train.head()

date  date_block_num  shop_id  item_id  item_price  item_cnt_day  \
0 2013-02-01               0       59    22154       999.0           1.0   
1 2013-10-01               0       59    22151       399.0           1.0   
2 2013-04-01               0       59     5603       699.0           1.0   
3 2013-01-19               0       59     5587       199.0           2.0   
4 2013-01-31               0       59     5613      5571.0           1.0   

   year  total_price  week_day       city sale_or_buy  
0  2013        999.0         4  Yaroslavl        sale  
1  2013        399.0         1  Yaroslavl        sale  
2  2013        699.0         0  Yaroslavl        sale  
3  2013        398.0         5  Yaroslavl        sale  
4  2013       5571.0         3  Yaroslavl        sale

In [30]:
train.item_id[0].isin(test.item_id)

AttributeError: 'numpy.int64' object has no attribute 'isin'