In [1]:
%run 006data-edits.ipynb

006data-edits.ipynb:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  {
006data-edits.ipynb:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  "cell_type": "code",
006data-edits.ipynb:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  "import pandas as pd\n",


In [2]:
train.head()

date  date_block_num  shop_id  item_id  item_price  item_cnt_day  \
0 2013-02-01               0       59    22154       999.0           1.0   
1 2013-10-01               0       59    22151       399.0           1.0   
2 2013-04-01               0       59     5603       699.0           1.0   
3 2013-01-19               0       59     5587       199.0           2.0   
4 2013-01-31               0       59     5613      5571.0           1.0   

   year  total_price  week_day       city sale_or_buy  in_test_item  \
0  2013        999.0         4  Yaroslavl        sale             1   
1  2013        399.0         1  Yaroslavl        sale             0   
2  2013        699.0         0  Yaroslavl        sale             0   
3  2013        398.0         5  Yaroslavl        sale             0   
4  2013       5571.0         3  Yaroslavl        sale             0   

   in_test_shop  
0             1  
1             1  
2             1  
3             1  
4             1

In [3]:
test.head()

ID  shop_id  item_id
0   0        5     5037
1   1        5     5320
2   2        5     5233
3   3        5     5232
4   4        5     5268

In [4]:
sub.head()

ID  item_cnt_month
0   0             0.5
1   1             0.5
2   2             0.5
3   3             0.5
4   4             0.5

## Train （途中練習も含む）

In [5]:
#以下　https://www.kaggle.com/koyohoriuchi/feature-engineering-xgboost/edit　を参考に

In [7]:
from itertools import product
matrix = []
cols = ['date_block_num', 'shop_id', 'item_id']
sales = train[train.date_block_num==1]
matrix.append(np.array(list(product([1], sales.shop_id.unique(), sales.item_id.unique())),dtype='int16'))

In [9]:
matrix = []
cols = ['date_block_num', 'shop_id', 'item_id']
for i in range(34):
    sales = train[train.date_block_num==i]
    matrix.append(np.array(list(product([i], sales.shop_id.unique(), sales.item_id.unique())),dtype='int16'))

In [10]:
matrix

[array([[    0,    59, 22154],
        [    0,    59, 22151],
        [    0,    59,  5603],
        ...,
        [    0,    45, 13566],
        [    0,    45, 12203],
        [    0,    45, 14941]], dtype=int16),
 array([[    1,    59,  4906],
        [    1,    59,  4907],
        [    1,    59,  4909],
        ...,
        [    1,     5, 18891],
        [    1,     5, 20190],
        [    1,     5, 15061]], dtype=int16),
 array([[    2,    59,  2929],
        [    2,    59,  2919],
        [    2,    59,  2854],
        ...,
        [    2,    58, 17344],
        [    2,    58,  1292],
        [    2,    58,   816]], dtype=int16),
 array([[    3,    59,  2730],
        [    3,    59,  2737],
        [    3,    59,  2760],
        ...,
        [    3,    58, 14416],
        [    3,    58, 14666],
        [    3,    58, 13991]], dtype=int16),
 array([[    4,    59, 22114],
        [    4,    59,  2678],
        [    4,    59,  2458],
        ...,
        [    4,    55,  1991],
       

In [11]:
p = list(product(['a', 'b', 'c'], range(3), [10, 20, 30]))
p

[('a', 0, 10),
 ('a', 0, 20),
 ('a', 0, 30),
 ('a', 1, 10),
 ('a', 1, 20),
 ('a', 1, 30),
 ('a', 2, 10),
 ('a', 2, 20),
 ('a', 2, 30),
 ('b', 0, 10),
 ('b', 0, 20),
 ('b', 0, 30),
 ('b', 1, 10),
 ('b', 1, 20),
 ('b', 1, 30),
 ('b', 2, 10),
 ('b', 2, 20),
 ('b', 2, 30),
 ('c', 0, 10),
 ('c', 0, 20),
 ('c', 0, 30),
 ('c', 1, 10),
 ('c', 1, 20),
 ('c', 1, 30),
 ('c', 2, 10),
 ('c', 2, 20),
 ('c', 2, 30)]

In [12]:
p_df = pd.DataFrame(p)
p_df

0  1   2
0   a  0  10
1   a  0  20
2   a  0  30
3   a  1  10
4   a  1  20
5   a  1  30
6   a  2  10
7   a  2  20
8   a  2  30
9   b  0  10
10  b  0  20
11  b  0  30
12  b  1  10
13  b  1  20
14  b  1  30
15  b  2  10
16  b  2  20
17  b  2  30
18  c  0  10
19  c  0  20
20  c  0  30
21  c  1  10
22  c  1  20
23  c  1  30
24  c  2  10
25  c  2  20
26  c  2  30

In [13]:
p_df2 = pd.DataFrame(np.vstack(p))
p_df2

0  1   2
0   a  0  10
1   a  0  20
2   a  0  30
3   a  1  10
4   a  1  20
5   a  1  30
6   a  2  10
7   a  2  20
8   a  2  30
9   b  0  10
10  b  0  20
11  b  0  30
12  b  1  10
13  b  1  20
14  b  1  30
15  b  2  10
16  b  2  20
17  b  2  30
18  c  0  10
19  c  0  20
20  c  0  30
21  c  1  10
22  c  1  20
23  c  1  30
24  c  2  10
25  c  2  20
26  c  2  30

In [15]:
matrix = []
cols = ['date_block_num', 'shop_id', 'item_id']
for i in range(34):
    sales = train[train.date_block_num == i]
    matrix.append(np.array(list(product([i], sales.shop_id.unique(), sales.item_id.unique())), dtype='int16'))
    
matrix

[array([[    0,    59, 22154],
        [    0,    59, 22151],
        [    0,    59,  5603],
        ...,
        [    0,    45, 13566],
        [    0,    45, 12203],
        [    0,    45, 14941]], dtype=int16),
 array([[    1,    59,  4906],
        [    1,    59,  4907],
        [    1,    59,  4909],
        ...,
        [    1,     5, 18891],
        [    1,     5, 20190],
        [    1,     5, 15061]], dtype=int16),
 array([[    2,    59,  2929],
        [    2,    59,  2919],
        [    2,    59,  2854],
        ...,
        [    2,    58, 17344],
        [    2,    58,  1292],
        [    2,    58,   816]], dtype=int16),
 array([[    3,    59,  2730],
        [    3,    59,  2737],
        [    3,    59,  2760],
        ...,
        [    3,    58, 14416],
        [    3,    58, 14666],
        [    3,    58, 13991]], dtype=int16),
 array([[    4,    59, 22114],
        [    4,    59,  2678],
        [    4,    59,  2458],
        ...,
        [    4,    55,  1991],
       

In [16]:
matrix = pd.DataFrame(np.vstack(matrix), columns=cols)
matrix.sort_values(cols,inplace=True)
matrix

date_block_num  shop_id  item_id
115247                 0        2       19
117882                 0        2       27
120565                 0        2       28
118943                 0        2       29
114667                 0        2       32
...                  ...      ...      ...
10676602              33       59    22162
10676601              33       59    22163
10676600              33       59    22164
10680714              33       59    22166
10676612              33       59    22167

[10913850 rows x 3 columns]

In [17]:
group = train.groupby(['date_block_num','shop_id','item_id'],).agg({'item_cnt_day': ['sum']})#この書き方覚えたい
group.columns = ['item_cnt_month']
group.reset_index(inplace=True)

group

date_block_num  shop_id  item_id  item_cnt_month
0                     0        2       27             1.0
1                     0        2       33             1.0
2                     0        2      317             1.0
3                     0        2      438             1.0
4                     0        2      471             2.0
...                 ...      ...      ...             ...
1609119              33       59    22087             6.0
1609120              33       59    22088             2.0
1609121              33       59    22091             1.0
1609122              33       59    22100             1.0
1609123              33       59    22102             1.0

[1609124 rows x 4 columns]

In [18]:
matrix_2 = pd.merge(matrix, group, on=cols, how='left')
matrix_2.item_cnt_month = matrix_2.item_cnt_month.fillna(0)
matrix_2 #trainの準備完了

date_block_num  shop_id  item_id  item_cnt_month
0                      0        2       19             0.0
1                      0        2       27             1.0
2                      0        2       28             0.0
3                      0        2       29             0.0
4                      0        2       32             0.0
...                  ...      ...      ...             ...
10913845              33       59    22162             0.0
10913846              33       59    22163             0.0
10913847              33       59    22164             0.0
10913848              33       59    22166             0.0
10913849              33       59    22167             0.0

[10913850 rows x 4 columns]

## Test

In [19]:
test

ID  shop_id  item_id
0            0        5     5037
1            1        5     5320
2            2        5     5233
3            3        5     5232
4            4        5     5268
...        ...      ...      ...
214195  214195       45    18454
214196  214196       45    16188
214197  214197       45    15757
214198  214198       45    19648
214199  214199       45      969

[214200 rows x 3 columns]

In [20]:
matrix_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10913850 entries, 0 to 10913849
Data columns (total 4 columns):
 #   Column          Dtype  
---  ------          -----  
 0   date_block_num  int16  
 1   shop_id         int16  
 2   item_id         int16  
 3   item_cnt_month  float64
dtypes: float64(1), int16(3)
memory usage: 229.0 MB


In [22]:
test.drop('ID',axis=1, inplace=True)
test['date_block_num'] = 34
test.head()

shop_id  item_id  date_block_num
0        5     5037              34
1        5     5320              34
2        5     5233              34
3        5     5232              34
4        5     5268              34

In [23]:
data = pd.concat([matrix_2, test],ignore_index=True, sort=False, keys=cols)
data

date_block_num  shop_id  item_id  item_cnt_month
0                      0        2       19             0.0
1                      0        2       27             1.0
2                      0        2       28             0.0
3                      0        2       29             0.0
4                      0        2       32             0.0
...                  ...      ...      ...             ...
11128045              34       45    18454             NaN
11128046              34       45    16188             NaN
11128047              34       45    15757             NaN
11128048              34       45    19648             NaN
11128049              34       45      969             NaN

[11128050 rows x 4 columns]

In [24]:
data['month'] = data.date_block_num % 12
data

date_block_num  shop_id  item_id  item_cnt_month  month
0                      0        2       19             0.0      0
1                      0        2       27             1.0      0
2                      0        2       28             0.0      0
3                      0        2       29             0.0      0
4                      0        2       32             0.0      0
...                  ...      ...      ...             ...    ...
11128045              34       45    18454             NaN     10
11128046              34       45    16188             NaN     10
11128047              34       45    15757             NaN     10
11128048              34       45    19648             NaN     10
11128049              34       45      969             NaN     10

[11128050 rows x 5 columns]

In [25]:
data = data.merge(shop_city, on='shop_id')
data

date_block_num  shop_id  item_id  item_cnt_month  month         city
0                      0        2       19             0.0      0       Adygea
1                      0        2       27             1.0      0       Adygea
2                      0        2       28             0.0      0       Adygea
3                      0        2       29             0.0      0       Adygea
4                      0        2       32             0.0      0       Adygea
...                  ...      ...      ...             ...    ...          ...
11128045              34       36    18454             NaN     10  Novosibirsk
11128046              34       36    16188             NaN     10  Novosibirsk
11128047              34       36    15757             NaN     10  Novosibirsk
11128048              34       36    19648             NaN     10  Novosibirsk
11128049              34       36      969             NaN     10  Novosibirsk

[11128050 rows x 6 columns]

In [26]:
items

item_name  item_id  \
0              ! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.)         D        0   
1      !ABBYY FineReader 12 Professional Edition Full...        1   
2          ***В ЛУЧАХ СЛАВЫ   (UNV)                    D        2   
3        ***ГОЛУБАЯ ВОЛНА  (Univ)                      D        3   
4            ***КОРОБКА (СТЕКЛО)                       D        4   
...                                                  ...      ...   
22165             Ядерный титбит 2 [PC, Цифровая версия]    22165   
22166    Язык запросов 1С:Предприятия  [Цифровая версия]    22166   
22167  Язык запросов 1С:Предприятия 8 (+CD). Хрустале...    22167   
22168                                Яйцо для Little Inu    22168   
22169                      Яйцо дракона (Игра престолов)    22169   

       item_category_id  
0                    40  
1                    76  
2                    40  
3                    40  
4                    40  
...                 ...  
22165                31  
22166                54  
22167                49  
22168                62  
22169                69  

[22170 rows x 3 columns]

In [27]:
data = data.merge(items[['item_id', 'item_category_id']], on='item_id')
data

date_block_num  shop_id  item_id  item_cnt_month  month  \
0                      0        2       19             0.0      0   
1                      0        3       19             0.0      0   
2                      0        4       19             0.0      0   
3                      0        6       19             0.0      0   
4                      0        7       19             0.0      0   
...                  ...      ...      ...             ...    ...   
11128045              34       49    12470             NaN     10   
11128046              34       39    12470             NaN     10   
11128047              34       48    12470             NaN     10   
11128048              34       34    12470             NaN     10   
11128049              34       36    12470             NaN     10   

                 city  item_category_id  
0              Adygea                40  
1          Balashikha                40  
2            Volzhsky                40  
3            Voronezh                40  
4            Voronezh                40  
...               ...               ...  
11128045       Tyumen                58  
11128046  RostovNaDon                58  
11128047        Tomsk                58  
11128048   N.Novgorod                58  
11128049  Novosibirsk                58  

[11128050 rows x 7 columns]

In [28]:
data.to_csv('data.csv', index=False)